const DATA_URL = 'https://raw.githubusercontent.com/RhoInc/data-library/master/data/clinical-trials/renderer-specific/adbds.csv';
const state = {};
let chart;
function uniq(a){ return [...new Set(a.filter(v => v !== undefined && v !== null && v !== ''))].sort((x,y)=>String(x).localeCompare(String(y), undefined, {numeric:true})); }
function mean(vals){ vals = vals.map(Number).filter(Number.isFinite); return vals.length ? vals.reduce((a,b)=>a+b,0)/vals.length : null; }
function el(tag, attrs={}, text=''){ const e=document.createElement(tag); Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v)); if(text) e.textContent=text; return e; }
function select(label, values, value){ const w=el('div',{class:'control'}); w.append(el('label',{},label)); const s=el('select'); values.forEach(v=>{const o=el('option',{value:v},v); if(v===value) o.selected=true; s.append(o);}); w.append(s); return [w,s]; }
function input(label, value=''){ const w=el('div',{class:'control'}); w.append(el('label',{},label)); const i=el('input',{type:'number', value}); w.append(i); return [w,i]; }
function table(rows, cols){ return `<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,50).map(r=>`<tr>${cols.map(c=>`<td>${r[c] ?? ''}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }
function participantNote(rows, allRows){ const ids=uniq(rows.map(d=>d.USUBJID)); const total=uniq(allRows.map(d=>d.USUBJID)).length; return `${ids.length} of ${total} participants shown (${total ? (100*ids.length/total).toFixed(1) : '0.0'}%).`; }

d3.csv(DATA_URL).then(data => { const measures=uniq(data.map(d=>d.TEST)); const app=document.getElementById('app'); app.innerHTML='<div class="controls"></div><div class="note" id="note"></div><div class="chartBox"><canvas id="chart"></canvas></div><div class="listing" id="listing"></div>'; const controls=app.querySelector('.controls'); const [mW,mS]=select('Measure',measures,measures[0]), [bW,bS]=select('Baseline Visit',uniq(data.map(d=>d.VISITN)),'1'), [cW,cS]=select('Comparison Visit',uniq(data.map(d=>d.VISITN)),uniq(data.map(d=>d.VISITN)).at(-1)), [aW,aS]=select('Treatment Group',['All',...uniq(data.map(d=>d.ARM))],'All'); controls.append(mW,bW,cW,aW); [mS,bS,cS,aS].forEach(x=>x.onchange=render); function render(){ const all=data.filter(d=>d.TEST===mS.value && d.STRESN); const rows=all.filter(d=>aS.value==='All'||d.ARM===aS.value); const ids=uniq(rows.map(d=>d.USUBJID)); const points=ids.map(id=>{const b=rows.find(d=>d.USUBJID===id&&d.VISITN===bS.value), c=rows.find(d=>d.USUBJID===id&&d.VISITN===cS.value); return b&&c?{x:+b.STRESN,y:+c.STRESN,id,change:+c.STRESN-+b.STRESN,ARM:c.ARM}:null}).filter(Boolean); document.getElementById('note').textContent=`${points.length} of ${ids.length} participants have baseline and comparison values.`; if(chart)chart.destroy(); chart=new Chart(document.getElementById('chart'),{type:'scatter',data:{datasets:[{label:mS.value,data:points,backgroundColor:'#2563eb'}]},options:{plugins:{title:{display:true,text:'Baseline vs comparison'},tooltip:{callbacks:{label:c=>`${c.raw.id}: ${c.raw.x.toFixed(1)} → ${c.raw.y.toFixed(1)} (Δ ${c.raw.change.toFixed(1)})`}}},scales:{x:{title:{display:true,text:bS.value}},y:{title:{display:true,text:cS.value}}},onClick:(e,active)=>{if(active.length){const r=points[active[0].index]; document.getElementById('listing').innerHTML=table([r],['id','ARM','x','y','change']);}}}})} render(); });
